from . import edi_procedure
from . import edi_event
from . import service_log
from . import res_config_custom
from . import edi_batch
from . import account_move
from . import edi_template
from . import res_partner
from . import stock_picking
from . import product_product
from . import edi_dashboard
from . import edi_tag
from . import edi_test
from . import edi_document_cancel
from . import edi_document_invalid
from . import edi_document_nomination