{
    'name'        : 'MSP SIFEN',
    'version'     : '0.2.3',
    'summary'     : "MSP SIFEN",
    'description' : "Estructura Básica de Vistas para Personalización",
    'author'      : "Martin Salcedo Pacheco",
    'website'     : 'https://www.gadolconsulting.com/',
    'depends'     : [
        'base',
        'account',
        'stock',
        'msp_service',
        'msp_branch',
        'msp_account_branch',
        'msp_stock_branch',
        'l10n_py',
        'l10n_py_edi',
        'msp_base',
        'msp_tools',
    ],
    'category'    : 'Customizations',
    'sequence'    : 10,
    'demo'        : [

    ],
    'data'        : [
        'data/ir_sequence.xml',
        'data/ir_cron.xml',
        'data/mail_template.xml',
        'data/ir_actions_server.xml',
        'data/edi_dashboard.xml',

        'security/ir_model_access.xml',

        'views/account_move.xml',
        'views/res_partner.xml',
        'views/edi_event.xml',
        'views/edi_procedure.xml',
        'views/edi_batch.xml',
        'views/edi_template.xml',
        'views/service_log.xml',
        'views/res_config_custom.xml',
        'views/stock_picking.xml',
        'views/edi_dashboard.xml',
        'views/edi_tag.xml',
        'views/ir_cron.xml',
        'views/edi_test.xml',
        'views/edi_document_cancel.xml',
        'views/edi_document_invalid.xml',
        'views/edi_document_nomination.xml',

        'entries/module_actions_act_window.xml',
        'entries/module_menu.xml',

        # 'scripts/edi.template.csv',
        # 'scripts/edi.procedure.csv',
    ],
    'installable' : True,
    'application' : False,
    'auto_install': False,
    'assets'      : {},
    'license'     : 'LGPL-3',
}
